apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/name: minio
    {{- include "cdc.labels" . | nindent 4 }}
type: Opaque
stringData:
  MINIO_ROOT_USER:     {{ .Values.minio.credentials.accessKey | quote }}
  MINIO_ROOT_PASSWORD: {{ .Values.minio.credentials.secretKey | quote }}
