apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/name: prometheus
    {{- include "cdc.labels" . | nindent 4 }}
spec:
  type: NodePort
  selector:
    {{- include "cdc.selectorLabels" "prometheus" | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.prometheus.port }}
      targetPort: {{ .Values.prometheus.port }}
      nodePort: {{ .Values.prometheus.service.nodePort }}
