{{- if .Values.orchestrator.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: orchestrator
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/name: orchestrator
    {{- include "cdc.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: orchestrator
    namespace: {{ .Values.global.namespace }}
roleRef:
  kind: Role
  name: orchestrator
  apiGroup: rbac.authorization.k8s.io
{{- end }}
