{{- if .Values.orchestrator.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: orchestrator-secret
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/name: orchestrator
    {{- include "cdc.labels" . | nindent 4 }}
type: Opaque
stringData:
  ALERT_WEBHOOK_URL: {{ .Values.orchestrator.alertWebhookUrl | quote }}
{{- end }}
