{{- if .Values.orchestrator.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: orchestrator
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/name: orchestrator
    {{- include "cdc.labels" . | nindent 4 }}
{{- end }}
